# Generated by Django 5.0 on 2026-02-13 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, help_text='Piscina/Palazzetto', max_length=200)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referee_report_uploaded', models.BooleanField(default=False)),
                ('ai_processed', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.league')),
                ('referees', models.ManyToManyField(blank=True, limit_choices_to={'role': 'referee'}, related_name='officiated_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GOAL', 'Gol'), ('EXPULSION', 'Espulsione'), ('TIMEOUT', 'Timeout')], max_length=20)),
                ('minute', models.IntegerField(help_text='Minuto di gioco')),
                ('quarter', models.IntegerField(default=1, help_text='Tempo/Quarto')),
                ('notes', models.CharField(blank=True, help_text="Es: 'Su rigore', 'Doppia espulsione'", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('player', models.ForeignKey(blank=True, limit_choices_to={'role': 'athlete'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='core.team')),
            ],
            options={
                'ordering': ['match', 'quarter', 'minute'],
            },
        ),
    ]
