# Generated by Django 5.0 on 2026-03-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='quarter_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Risultato per tempi: {tempo: [home, away]}'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='is_penalty',
            field=models.BooleanField(default=False, help_text='Evento legato a un tiro di rigore'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='is_superiority',
            field=models.BooleanField(default=False, help_text='Evento avvenuto in superiorità/inferiorità'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('GOAL', 'Gol (Azione)'), ('PENALTY_GOAL', 'Gol (Rigore)'), ('EXCLUSION_20', 'Espulsione (20")'), ('EXCLUSION_DEF', 'Espulsione Definitiva'), ('TIMEOUT', 'Timeout'), ('SAVE', 'Parata'), ('MISS', 'Errore')], max_length=20),
        ),
    ]
