# Generated by Django 5.0 on 2026-03-23 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_quarter_scores_matchevent_is_penalty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Referto in PDF o Immagine', upload_to='match_reports/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Caricato (In attesa)'), ('PROCESSING', 'In Elaborazione OCR'), ('EXTRACTED', 'Dati Estratti (Da Revisionare)'), ('VALIDATED', 'Validato (Approvato Admin)'), ('PUBLISHED', 'Pubblicato (Statistiche Aggiornate)'), ('REJECTED', 'Rifiutato/Errore')], default='UPLOADED', max_length=20)),
                ('raw_extracted_data', models.JSONField(blank=True, default=dict, help_text="Payload JSON grezzo restituito dall'engine OCR")),
                ('normalized_data', models.JSONField(blank=True, default=dict, help_text="Dati normalizzati/corretti pronti per l'inserimento")),
                ('validation_notes', models.TextField(blank=True, help_text="Note dell'admin (es. 'Manca la firma', 'Gol errato nel Q3')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='matches.match')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referto Match',
                'verbose_name_plural': 'Referti Match',
                'ordering': ['-created_at'],
            },
        ),
    ]
