# Generated by Django 5.0 on 2026-03-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_matchreport_published_at_matchreport_published_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='internal_notes',
            field=models.TextField(blank=True, help_text="Note interne per lo staff (non visibili all'uploader)"),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='validation_notes',
            field=models.TextField(blank=True, help_text='Note di validazione (visibili se necessario)'),
        ),
    ]
