# Generated by Django 5.0 on 2026-03-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_matchreport_internal_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='raw_api_response',
            field=models.TextField(blank=True, help_text='The exact, untouched JSON string from the OCR provider'),
        ),
    ]
