# Generated by Django 5.0 on 2026-03-26 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_matchreport_raw_api_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='RFC822 Message-ID', max_length=255, unique=True)),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.UUIDField(blank=True, default=None, help_text='Optional UUID from external provider', null=True)),
            ],
            options={
                'verbose_name': 'Email Inbound',
                'verbose_name_plural': 'Emails Inbound',
            },
        ),
        migrations.AddField(
            model_name='matchreport',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash del file per evitare duplicati', max_length=64),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata aggiuntivi (es: subject email, sender)'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manuale'), ('EMAIL', 'Email')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='inbound_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='matches.inboundemail'),
        ),
    ]
