# Generated by Django 5.0 on 2026-03-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_inboundemail_matchreport_file_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='ai_processed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='referee_report_uploaded',
        ),
        migrations.AddField(
            model_name='match',
            name='has_report',
            field=models.BooleanField(default=False, help_text='La partita ha un referto associato (File o Digitale)'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_data_verified',
            field=models.BooleanField(default=False, help_text='I dati sono stati verificati e approvati'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='source_channel',
            field=models.CharField(choices=[('FILE', 'Caricamento File / OCR'), ('DIGITAL', 'Referto Digitale Nativo')], default='FILE', max_length=10),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='file',
            field=models.FileField(blank=True, help_text='Referto in PDF o Immagine', null=True, upload_to='match_reports/'),
        ),
    ]
