# Generated by Django 5.0 on 2026-03-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sport_default_periods_sport_period_label_and_more'),
        ('matches', '0008_remove_match_ai_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(help_text="Codice dell'evento (mappato su SportEventConfig)", max_length=50),
        ),
        migrations.CreateModel(
            name='SportEventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(help_text='Codice interno (es: GOAL, YELLOW_CARD)', max_length=50)),
                ('label', models.CharField(help_text="Etichetta visualizzata (es: 'Gol', 'Cartellino Giallo')", max_length=100)),
                ('is_score', models.BooleanField(default=False, help_text="Se l'evento incrementa il punteggio della squadra")),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_configs', to='core.sport')),
            ],
            options={
                'unique_together': {('sport', 'event_code')},
            },
        ),
    ]
