# Generated by Django 5.0 on 2026-04-13 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_matchevent_event_type_sporteventconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-match_date'], 'verbose_name': 'Partita', 'verbose_name_plural': 'Partite'},
        ),
        migrations.AlterModelOptions(
            name='matchreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Referto', 'verbose_name_plural': '📄 Referti Match'},
        ),
        migrations.AddField(
            model_name='matchreport',
            name='in_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='in_review_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_reviewing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Caricato (In attesa)'), ('PROCESSING', 'In Elaborazione OCR'), ('EXTRACTED', 'Dati Estratti (Da Revisionare)'), ('VALIDATED', 'Validato (Approvato Admin)'), ('PUBLISHED', 'Pubblicato (Statistiche Aggiornate)'), ('NEEDS_REVIEW', 'Revisione Tecnica Necessaria'), ('REJECTED', 'Rifiutato/Errore')], default='UPLOADED', max_length=20),
        ),
    ]
