# Generated by Django 5.0 on 2026-04-15 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_matchreportauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_query', models.TextField()),
                ('response_type', models.CharField(help_text='answer, error, insufficient_data', max_length=50)),
                ('response_text', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('time_range', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='homepage', max_length=50)),
                ('matched_athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Query Log',
                'verbose_name_plural': '🤖 AI Query Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
