# Generated by Django 5.0 on 2026-04-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_aiquerylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreportauditlog',
            name='new_status',
            field=models.CharField(blank=True, help_text='Nuovo stato', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matchreportauditlog',
            name='old_status',
            field=models.CharField(blank=True, help_text='Stato precedente', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matchreportauditlog',
            name='reason',
            field=models.TextField(blank=True, help_text='Motivazione del cambio stato o modifica'),
        ),
    ]
