# Generated by Django 5.0 on 2026-04-16 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_matchreportauditlog_new_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRRawResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(help_text='ID del provider (es: openai-gpt4o)', max_length=100)),
                ('raw_response', models.JSONField(help_text='Risposta JSON completa del provider')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, help_text='ID univoco della richiesta fornito dal provider', max_length=255)),
                ('latency_ms', models.IntegerField(blank=True, help_text='Latenza della richiesta in millisecondi', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_responses', to='matches.matchreport')),
            ],
            options={
                'verbose_name': 'Risposta Raw OCR',
                'verbose_name_plural': 'Risposte Raw OCR',
                'ordering': ['-created_at'],
            },
        ),
    ]
