# Generated by Django 5.0 on 2026-04-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_ocrrawresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Bozza (Digitale)'), ('UPLOADED', 'Caricato (In attesa)'), ('PROCESSING', 'In Elaborazione OCR'), ('EXTRACTED', 'Dati Estratti (Da Revisionare)'), ('VALIDATED', 'Validato (Approvato Admin)'), ('PUBLISHED', 'Pubblicato (Statistiche Aggiornate)'), ('NEEDS_REVIEW', 'Revisione Tecnica Necessaria'), ('REJECTED', 'Rifiutato/Errore')], default='UPLOADED', max_length=20),
        ),
    ]
