# Generated by Django 5.0 on 2026-04-19 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_alter_matchreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreport',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='matches.match'),
        ),
    ]
