# Generated by Django 5.0 on 2026-07-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_alter_matchreport_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OCRRawResponse',
        ),
    ]
