# Generated by Django 5.0 on 2026-07-19 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_delete_ocrrawresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='referee_signature',
            field=models.CharField(blank=True, help_text='Firma arbitro (nome e cognome) digitata alla chiusura del referto digitale', max_length=200),
        ),
        migrations.CreateModel(
            name='MatchJuryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Token URL-safe ad alta entropia (secrets, >=32 byte)', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Attivo'), ('CONSUMED', 'Consumato (referto chiuso)'), ('REVOKED', 'Revocato'), ('EXPIRED', 'Scaduto (backstop 7 giorni)')], db_index=True, default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Backstop = created_at + EXPIRY_DAYS')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff/admin che ha emesso il link (null se sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_jury_links', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_links', to='matches.match')),
                ('report', models.ForeignKey(blank=True, help_text='Referto chiuso dal link (valorizzato al consume)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jury_links', to='matches.matchreport')),
            ],
            options={
                'verbose_name': 'Link Giuria Partita',
                'verbose_name_plural': 'Link Giuria Partite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='matchjurylink',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('match',), name='uniq_active_jury_link_per_match'),
        ),
    ]
