# Generated by Django 5.0 on 2026-07-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_matchreport_referee_signature_matchjurylink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='ocr_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Tentativi di elaborazione OCR (incrementato al claim del worker)'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='ocr_error',
            field=models.TextField(blank=True, help_text='Ultimo errore tecnico OCR (diagnostica worker)'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='ocr_next_attempt_at',
            field=models.DateTimeField(blank=True, help_text='Non eleggibile al claim prima di questo istante (backoff retry)', null=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='ocr_queued_at',
            field=models.DateTimeField(blank=True, help_text='Istante di accodamento (ordinamento FIFO)', null=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='ocr_started_at',
            field=models.DateTimeField(blank=True, help_text='Istante del claim (base per lo stale detection)', null=True),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Bozza (Digitale)'), ('UPLOADED', 'Caricato (In attesa)'), ('QUEUED', 'In Coda OCR'), ('PROCESSING', 'In Elaborazione OCR'), ('EXTRACTED', 'Dati Estratti (Da Revisionare)'), ('VALIDATED', 'Validato (Approvato Admin)'), ('PUBLISHED', 'Pubblicato (Statistiche Aggiornate)'), ('NEEDS_REVIEW', 'Revisione Tecnica Necessaria'), ('REJECTED', 'Rifiutato/Errore')], default='UPLOADED', max_length=20),
        ),
    ]
