# Generated by Django 5.0 on 2026-07-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_ocr_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='publication_level',
            field=models.CharField(choices=[('FULL', 'Completo (punteggio, parziali ed eventi)'), ('SCORE_ONLY', 'Solo punteggio e parziali verificati (eventi non disponibili)')], default='FULL', help_text="Fin dove il referto e' certificato al publish: FULL (con eventi) o SCORE_ONLY (solo punteggio/parziali).", max_length=12),
        ),
    ]
