# Generated by Django 5.0 on 2026-07-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_matchreport_publication_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='regulation_article',
            field=models.CharField(blank=True, help_text="Articolo di regolamento verbatim (es. '9.13'), solo per espulsione definitiva", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='sanction_sigla',
            field=models.CharField(blank=True, help_text="Sigla verbatim della sanzione come scritta sul referto (es. 'EDCS')", max_length=50, null=True),
        ),
    ]
