# Generated by Django 5.0 on 2026-02-23 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_league_slug'),
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.JSONField(blank=True, help_text="Es: {'freq': 'WEEKLY', 'days': [0, 2, 4], 'until': '2026-06-30'}", null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='trainings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='core.society')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Note specifiche per questa sessione')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='management.training')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('PRESENT', 'Presente'), ('ABSENT', 'Assente'), ('JUSTIFIED', 'Assente Giustificato')], default='PENDING', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='management.trainingoccurrence')),
            ],
            options={
                'unique_together': {('occurrence', 'user')},
            },
        ),
    ]
