# Generated by Django 5.0 on 2026-02-23 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_training_trainingoccurrence_trainingattendance'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('SENT_PRIVATE', 'Inviata Privata'), ('PUBLISHED', 'Pubblicata Ufficiale'), ('LOCKED', 'Bloccata (Gara iniziata)')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='convocations/')),
                ('ai_check_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capitano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_captain', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_convocations', to=settings.AUTH_USER_MODEL)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convocation', to='matches.match')),
                ('vicecapitano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_vice_captain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConvocationNominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField(default=False, help_text='Se fa parte dei 7 titolari')),
                ('convocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='management.convocation')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocation_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('convocation', 'player')},
            },
        ),
    ]
