# Generated by Django 5.0 on 2026-03-21 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_sports'),
        ('management', '0004_convocation_reminders_sent_chatmessage_post_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Es: RECC-X12-Y34', max_length=50, unique=True)),
                ('role', models.CharField(choices=[('PRESIDENT', 'Presidente (Società)'), ('HEAD_COACH', 'Allenatore Capo (Squadra)'), ('ASSISTANT_COACH', 'Vice Allenatore (Squadra)'), ('PLAYER', 'Giocatore (Squadra)')], default='PLAYER', max_length=20)),
                ('max_uses', models.IntegerField(default=50)),
                ('current_uses', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activation_codes', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_codes', to='core.society')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activation_codes', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRESIDENT', 'Presidente (Società)'), ('HEAD_COACH', 'Allenatore Capo (Squadra)'), ('ASSISTANT_COACH', 'Vice Allenatore (Squadra)'), ('PLAYER', 'Giocatore (Squadra)')], default='PLAYER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('APPROVED', 'Approvata'), ('REJECTED', 'Respinta')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Note del Club Admin in fase di approvazione/rifiuto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='core.society')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='core.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Richiesta Membership',
                'verbose_name_plural': 'Richieste Membership',
            },
        ),
    ]
