# Generated by Django 5.0 on 2026-03-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sport_default_periods_sport_period_label_and_more'),
        ('management', '0005_activationcode_membershiprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.society'),
        ),
    ]
