# Generated by Django 5.0 on 2026-03-28 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_auditlog_society'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotBug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('S1', 'S1 — Blocker'), ('S2', 'S2 — Critical'), ('S3', 'S3 — Major'), ('S4', 'S4 — Minor')], default='S3', max_length=2)),
                ('role_context', models.CharField(blank=True, help_text='Role/context when bug was found', max_length=100)),
                ('observed_behavior', models.TextField(help_text='What actually happened')),
                ('expected_behavior', models.TextField(help_text='What should have happened')),
                ('reproducibility', models.CharField(choices=[('ALWAYS', 'Always'), ('SOMETIMES', 'Sometimes'), ('RARE', 'Rare'), ('ONCE', 'Once')], default='ALWAYS', max_length=10)),
                ('workaround', models.TextField(blank=True, help_text='Known workaround if any')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('TRIAGED', 'Triaged'), ('IN_PROGRESS', 'In Progress'), ('MITIGATED', 'Mitigated'), ('CLOSED', 'Closed'), ('VERIFIED', 'Verified')], default='NEW', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Assigned developer/staff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_bugs_owned', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_bugs_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pilot Bug',
                'verbose_name_plural': 'Pilot Bugs',
                'ordering': ['severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PilotDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Pilot day date', unique=True)),
                ('status', models.CharField(choices=[('GREEN', '🟢 Green — nominal'), ('YELLOW', '🟡 Yellow — issues present'), ('RED', '🔴 Red — blocked / critical')], default='GREEN', max_length=10)),
                ('blockers', models.TextField(blank=True, help_text='Active blockers')),
                ('workarounds', models.TextField(blank=True, help_text='Active workarounds in place')),
                ('notes', models.TextField(blank=True, help_text='Key observations for the day')),
                ('next_day_decision', models.TextField(blank=True, help_text='Operational decision for the next day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(help_text='Staff member responsible for this day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pilot Daily Log',
                'verbose_name_plural': 'Pilot Daily Logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PilotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Who provided this feedback', max_length=100)),
                ('flow_step', models.CharField(blank=True, help_text='Which flow/step this relates to', max_length=100)),
                ('summary', models.TextField(help_text='Feedback summary')),
                ('impact', models.TextField(blank=True, help_text='Impact on user experience or operations')),
                ('category', models.CharField(choices=[('UX_COPY', 'UX / Copy'), ('ONBOARDING', 'Onboarding'), ('VISIBILITY_STATE', 'Visibility / State'), ('OPERATIONAL_PROCESS', 'Operational Process'), ('FUTURE_REQUEST', 'Future Request')], default='UX_COPY', max_length=25)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('PLANNED', 'Planned'), ('DONE', 'Done'), ('WONT_FIX', "Won't Fix")], default='NEW', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_feedback_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pilot Feedback',
                'verbose_name_plural': 'Pilot Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PilotReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('review_type', models.CharField(choices=[('DAY_7', 'Day 7 Review'), ('DAY_14', 'Day 14 Review')], max_length=10)),
                ('what_worked', models.TextField(help_text='What went well during this period')),
                ('blockers_summary', models.TextField(blank=True, help_text='Summary of blockers encountered')),
                ('recurring_issues', models.TextField(blank=True, help_text='Issues that kept coming back')),
                ('staff_load', models.TextField(blank=True, help_text='Assessment of staff workload')),
                ('recommendation', models.CharField(choices=[('CONTINUE', 'Continue'), ('REDUCED_SCOPE', 'Continue with Reduced Scope'), ('EXTEND', 'Extend to Day 14'), ('SUSPEND', 'Suspend Part of Flow')], max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_reviews_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pilot Review',
                'verbose_name_plural': 'Pilot Reviews',
                'ordering': ['-review_date'],
            },
        ),
    ]
