# Generated by Django 5.0 on 2026-05-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_pilot_ops_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
