# Generated by Django 5.0 on 2026-06-09 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_league_season_fk'),
        ('management', '0009_membership_end_date_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='core.season'),
        ),
    ]
