# Generated by Django 5.0 on 2026-06-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_backfill_membership_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='coach_change_note',
            field=models.TextField(blank=True, default='', help_text="Cambio coach in corso di stagione (chi→chi, quando): nota libera, non struttura l'attribuzione."),
        ),
    ]
