# Generated by Django 5.0 on 2026-06-10 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_league_season_fk'),
        ('management', '0012_membership_coach_change_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'society', 'team', 'role', 'season'), name='uniq_membership_user_society_team_role_season'),
        ),
    ]
