# Generated by Django 5.0 on 2026-06-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='membership_end_date_after_start',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='start_date',
        ),
    ]
