# Generated by Django 5.0 on 2026-06-11 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_category_fields'),
        ('management', '0015_membership_season_notnull'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_loan',
            field=models.BooleanField(default=False, help_text="Membership di prestito: il tesseramento resta alla società d'origine."),
        ),
        migrations.AddField(
            model_name='membership',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Attivo'), ('ENDED', 'Concluso')], default='', help_text='Stato del prestito (etichetta, non macchina a stati). Vuoto per membership non-prestito.', max_length=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='tesseramento_society',
            field=models.ForeignKey(blank=True, help_text="Società d'origine del tesseramento (solo per prestiti).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loaned_out_memberships', to='core.society'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_loan', False), ('loan_status', ''), ('tesseramento_society__isnull', True)), models.Q(('is_loan', True), ('tesseramento_society__isnull', False), models.Q(('loan_status', ''), _negated=True)), _connector='OR'), name='membership_loan_fields_coherent'),
        ),
    ]
