# Generated by Django 5.0 on 2026-06-20 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_normalizza_slug_serie_b'),
        ('management', '0016_membership_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RICHIESTA_INVIATA', 'Richiesta inviata'), ('IN_ATTESA_SOCIETA', 'In attesa società'), ('CONFERMATA_SOCIETA', 'Confermata società'), ('IN_ATTESA_CLICK_GENITORE', 'In attesa click'), ('CERTIFICATA', 'Certificata'), ('RIFIUTATA', 'Rifiutata'), ('SCADUTA', 'Scaduta')], default='RICHIESTA_INVIATA', max_length=30)),
                ('token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('society_responded_at', models.DateTimeField(blank=True, null=True)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(help_text="L'atleta figlio (già nel sistema): v1 solo atleti esistenti.", on_delete=django.db.models.deletion.CASCADE, related_name='child_certifications', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(help_text='Il genitore/fan che richiede la certificazione.', on_delete=django.db.models.deletion.CASCADE, related_name='parent_certifications', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(help_text='Società destinataria: quella in cui il figlio è tesserato.', on_delete=django.db.models.deletion.CASCADE, related_name='parent_certifications', to='core.society')),
            ],
            options={
                'verbose_name': 'Certificazione genitore',
                'verbose_name_plural': 'Certificazioni genitore',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='parentcertification',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CERTIFICATA', 'RIFIUTATA', 'SCADUTA']), _negated=True), fields=('parent', 'child'), name='uniq_parentcert_open_per_parent_child'),
        ),
    ]
