/opt/2salti/logs/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0640 alberto alberto
    sharedscripts
    postrotate
        systemctl reload 2salti.service 2salti-staging.service 2salti-dev.service > /dev/null 2>/dev/null || true
    endscript
}
