# Generated by Django 5.0 on 2026-02-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('hex_color', models.CharField(default='#00ffff', help_text='Colore tema (es: #00ffff)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Nome icona Heroicons', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='societies/')),
                ('history', models.TextField(blank=True, help_text='Storia della società')),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('sponsors', models.JSONField(blank=True, default=list)),
                ('setup_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='societies', to='core.sport')),
            ],
            options={
                'verbose_name_plural': 'Societies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Es: Serie A1 Maschile', max_length=100)),
                ('category', models.CharField(choices=[('U10', 'Under 10'), ('U12', 'Under 12'), ('U14', 'Under 14'), ('U16', 'Under 16'), ('U18', 'Under 18'), ('U20', 'Under 20'), ('SENIOR', 'Prima Squadra')], max_length=10)),
                ('season', models.CharField(default='2024-2025', help_text='Es: 2024-2025', max_length=9)),
                ('group_name', models.CharField(blank=True, help_text='Es: Girone A, Girone B', max_length=50)),
                ('level', models.IntegerField(default=1, help_text='1=A1, 2=A2, 3=B, ecc.')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='core.sport')),
            ],
            options={
                'ordering': ['sport', 'level', 'group_name'],
                'unique_together': {('name', 'season', 'group_name')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('U10', 'Under 10'), ('U12', 'Under 12'), ('U14', 'Under 14'), ('U16', 'Under 16'), ('U18', 'Under 18'), ('U20', 'Under 20'), ('SENIOR', 'Prima Squadra')], max_length=10)),
                ('name', models.CharField(blank=True, help_text='Auto-generato: Society + Category', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='core.league')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.society')),
            ],
            options={
                'ordering': ['society', 'category'],
                'unique_together': {('society', 'category')},
            },
        ),
    ]
