# Generated by Django 5.0 on 2026-02-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
