# Generated by Django 5.0 on 2026-03-26 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(help_text='Es: 2024-2025', max_length=9)),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_diff', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persisted_standings', to='core.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persisted_standings', to='core.team')),
            ],
            options={
                'ordering': ['rank', '-points', '-goal_diff', '-goals_for'],
                'unique_together': {('league', 'team', 'season')},
            },
        ),
    ]
