# Generated by Django 5.0 on 2026-03-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_leaguestanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='default_periods',
            field=models.IntegerField(default=4, help_text='Numero di frazioni di gioco predefinite (es: 4 per WP)'),
        ),
        migrations.AddField(
            model_name='sport',
            name='period_label',
            field=models.CharField(default='Tempo', help_text="Nome della frazione (es: 'Tempo', 'Set', 'Quarto')", max_length=50),
        ),
        migrations.AddField(
            model_name='sport',
            name='point_system',
            field=models.JSONField(blank=True, default=dict, help_text="Configurazione punti classifica. Es: {'win': 3, 'draw': 1, 'loss': 0}"),
        ),
    ]
