# Generated by Django 5.0 on 2026-03-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sport_default_periods_sport_period_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='last_rebuild_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='needs_rebuild',
            field=models.BooleanField(default=False, help_text='Indica se la classifica deve essere ricalcolata'),
        ),
    ]
