# Generated by Django 5.0 on 2026-04-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_league_last_rebuild_at_league_needs_rebuild'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['sport', 'level', 'group_name'], 'verbose_name': 'Campionato', 'verbose_name_plural': '🏆 Campionati'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['name'], 'verbose_name': 'Sport', 'verbose_name_plural': '🏅 Sport'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['society', 'category'], 'verbose_name': 'Squadra', 'verbose_name_plural': '👥 Squadre'},
        ),
        migrations.AlterField(
            model_name='society',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
