# Generated by Django 5.0 on 2026-06-07 17:51

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bonifica_season_slash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='season',
            field=models.CharField(default='2025/2026', help_text='Es: 2025/2026', max_length=9, validators=[core.validators.validate_season_format]),
        ),
        migrations.AlterField(
            model_name='leaguestanding',
            name='season',
            field=models.CharField(help_text='Es: 2025/2026', max_length=9, validators=[core.validators.validate_season_format]),
        ),
    ]
