# Generated by Django 5.0 on 2026-06-09 17:29

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_league_season_alter_leaguestanding_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Es: 2025/2026', max_length=9, validators=[core.validators.validate_season_format])),
                ('is_current', models.BooleanField(default=False, help_text='Stagione corrente per questo sport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.sport')),
            ],
            options={
                'verbose_name': 'Stagione',
                'verbose_name_plural': '🗓 Stagioni',
                'ordering': ['sport', '-label'],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('sport', 'label'), name='unique_season_per_sport'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('sport',), name='unique_current_season_per_sport'),
        ),
    ]
