# Generated by Django 5.0 on 2026-06-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_league_season_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_type',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('U10', 'U10'), ('U12', 'U12'), ('U14', 'U14'), ('U16', 'U16'), ('U18', 'U18'), ('U20', 'U20')], help_text='Tipo lega (A1–D grandi, U10–U20 giovanili). Vuoto = non classificata.', max_length=3, null=True),
        ),
    ]
