# Generated by Django 5.0 on 2026-06-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rifusione_scaffolding_senior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['society', 'name'], 'verbose_name': 'Squadra', 'verbose_name_plural': '👥 Squadre'},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='league',
            name='category',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, help_text='Auto-generato: Society + tipo lega', max_length=200),
        ),
        migrations.RemoveField(
            model_name='team',
            name='category',
        ),
    ]
