# Generated by Django 5.0 on 2026-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_normalizza_slug_serie_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='hex_color',
            field=models.CharField(default='#2563eb', help_text='Colore tema (es: #2563eb)', max_length=7),
        ),
    ]
