# Generated by Django 5.0 on 2026-06-30 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_pallanuoto_hex_color_blue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True, help_text='URL del logo (seed/admin-only nel pilota).')),
                ('url', models.URLField(blank=True, help_text='Sito esterno dello sponsor (link sul logo).')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione (crescente).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(help_text='Stagione di validità: gli sponsor si mostrano nella stagione corrente.', on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='core.season')),
                ('society', models.ForeignKey(help_text='Società a cui appartiene lo sponsor.', on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_entries', to='core.society')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': '🤝 Sponsor',
                'ordering': ['order', 'name'],
            },
        ),
    ]
