# Generated by Django 5.0 on 2026-07-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='is_comped',
            field=models.BooleanField(default=False, help_text='Entitlement CLUB_PRO concesso gratuitamente (override su tier).'),
        ),
        migrations.AddField(
            model_name='society',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('CLUB_PRO', 'Club Pro')], default='FREE', help_text='Tier società. Cambiato SOLO via core.services.entitlement_service (seam).', max_length=10),
        ),
    ]
