# Generated by Django 5.0 on 2026-07-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_society_tier_comped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='is_comped',
            field=models.BooleanField(db_default=models.Value(False), default=False, help_text='Entitlement CLUB_PRO concesso gratuitamente (override su tier).'),
        ),
        migrations.AlterField(
            model_name='society',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('CLUB_PRO', 'Club Pro')], db_default=models.Value('FREE'), default='FREE', help_text='Tier società. Cambiato SOLO via core.services.entitlement_service (seam).', max_length=10),
        ),
    ]
