# Generated by Django 5.0 on 2026-07-21 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_orphan_sports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text="La grafia così com'è scritta sulla fonte (maiuscole e punteggiatura incluse).", max_length=200)),
                ('alias_normalized', models.CharField(db_index=True, editable=False, help_text="Forma normalizzata dell'alias: garantisce l'unicità case-insensitive ed è la chiave con cui la discovery cerca.", max_length=200, unique=True)),
                ('origin', models.CharField(choices=[('REFERTO', 'Grafia vista su un referto cartaceo'), ('ANAGRAFICA', 'Grafia di fonte anagrafica/ufficiale'), ('ALTRO', 'Altra origine (specificare nella nota)')], default='REFERTO', help_text='Da dove viene questa grafia.', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Su quale foglio/fonte è stata vista, e ogni altro dettaglio utile a riverificarla.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text="Chi ha inserito l'alias. Vuoto per gli inserimenti di sistema.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_aliases_created', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='Squadra a cui la grafia si riferisce.', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.team')),
            ],
            options={
                'verbose_name': 'Alias squadra',
                'verbose_name_plural': '🔤 Alias squadra',
                'ordering': ['team__name', 'alias'],
            },
        ),
    ]
