# Generated by Django 5.0 on 2026-02-13 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(help_text='Es: 2023-2024', max_length=9)),
                ('entity_type', models.CharField(choices=[('athlete', 'Atleta'), ('team', 'Squadra')], max_length=20)),
                ('stats_data', models.JSONField(help_text='Statistiche complete della stagione')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_archives', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_archives', to='core.team')),
            ],
            options={
                'ordering': ['-season'],
                'unique_together': {('season', 'entity_type', 'athlete', 'team')},
            },
        ),
    ]
