# Generated by Django 5.0 on 2026-06-07 17:51

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonarchive',
            name='season',
            field=models.CharField(help_text='Es: 2025/2026', max_length=9, validators=[core.validators.validate_season_format]),
        ),
    ]
