# Generated by Django 5.0 on 2026-02-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='license_type',
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='specialization_other',
            field=models.CharField(blank=True, help_text='Specifica se hai scelto Altro', max_length=100),
        ),
        migrations.AddField(
            model_name='refereeprofile',
            name='license_level_other',
            field=models.CharField(blank=True, help_text='Specifica se hai scelto Altro', max_length=100),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('portieri', 'Portieri'), ('attacco', 'Attacco'), ('difesa', 'Difesa'), ('atletica', 'Preparazione Atletica'), ('tattica', 'Tattica'), ('giovanile', 'Settore Giovanile'), ('altro', 'Altro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='refereeprofile',
            name='license_level',
            field=models.CharField(blank=True, choices=[('regionale', 'Regionale'), ('interregionale', 'Interregionale'), ('nazionale', 'Nazionale'), ('internazionale', 'Internazionale'), ('altro', 'Altro')], max_length=50),
        ),
    ]
