# Generated by Django 5.0 on 2026-03-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_coachprofile_license_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Non verificato'), ('VERIFIED', 'Verificato')], default='UNVERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('INACTIVE', 'Inattivo'), ('ACTIVE', 'Attivo')], default='INACTIVE', max_length=20),
        ),
    ]
