# Generated by Django 5.0 on 2026-03-24 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_identity_status_user_identity_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('APPROVED', 'Approvato'), ('REJECTED', 'Rifiutato')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Note sulla richiesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_links', to='accounts.athleteprofile')),
                ('coach_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_links', to='accounts.coachprofile')),
                ('referee_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_links', to='accounts.refereeprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collegamento Profilo',
                'verbose_name_plural': 'Collegamenti Profilo',
                'unique_together': {('user', 'athlete_profile', 'coach_profile', 'referee_profile')},
            },
        ),
    ]
