# Generated by Django 5.0 on 2026-04-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountprofilelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.CharField(choices=[('NONE', 'Nessuno'), ('UPLOADER', 'Collaboratore (Solo Upload)'), ('REVIEWER', 'Reviewer (Edit/Validazione)'), ('PUBLISHER', 'Publisher (Pubblicazione)'), ('SUPERADMIN', 'Super Amministratore')], default='NONE', max_length=20),
        ),
    ]
