# Generated by Django 5.0 on 2026-06-20

from django.db import migrations


def backfill_fan_profiles(apps, schema_editor):
    """Crea un FanProfile per ogni User role='fan' che ancora non ne ha uno.

    Idempotente: get_or_create non duplica se rilanciato. Logga solo pk e
    conteggi (nessuna PII). Usa i modelli storici via apps.get_model.
    """
    import logging

    logger = logging.getLogger(__name__)
    User = apps.get_model('accounts', 'User')
    FanProfile = apps.get_model('accounts', 'FanProfile')

    created = 0
    for user_pk in User.objects.filter(role='fan').values_list('pk', flat=True):
        _, was_created = FanProfile.objects.get_or_create(user_id=user_pk)
        if was_created:
            created += 1
            logger.info("[backfill_fanprofile] creato FanProfile per user_pk=%s", user_pk)

    logger.info("[backfill_fanprofile] completato: %s FanProfile creati", created)


def reverse_noop(apps, schema_editor):
    """Reverse no-op: la reverse della migration di schema (0006) elimina
    comunque la tabella FanProfile. Un backfill idempotente non ha bisogno di
    sapere quali righe ha creato per essere annullato."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fanprofile'),
    ]

    operations = [
        migrations.RunPython(backfill_fan_profiles, reverse_noop),
    ]
