# Generated by Django 5.0 on 2026-07-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_backfill_fanprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_payment_done',
            field=models.BooleanField(default=False, help_text="Ha completato lo step di pagamento nell'onboarding (mock 0,50€)."),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('FREEMIUM', 'Freemium'), ('PREMIUM', 'Premium')], default='FREEMIUM', help_text='Piano premium. Cambiato SOLO via core.services.entitlement_service (seam).', max_length=10),
        ),
    ]
