# Generated by Django 5.0 on 2026-07-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_plan_onboarding_payment_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='onboarding_payment_done',
            field=models.BooleanField(db_default=models.Value(False), default=False, help_text="Ha completato lo step di pagamento nell'onboarding (mock 0,50€)."),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('FREEMIUM', 'Freemium'), ('PREMIUM', 'Premium')], db_default=models.Value('FREEMIUM'), default='FREEMIUM', help_text='Piano premium. Cambiato SOLO via core.services.entitlement_service (seam).', max_length=10),
        ),
    ]
