# Generated by Django 5.0 on 2026-07-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_decouple_onboarding_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_status',
        ),
    ]
